#!/bin/bash

input_file=$1
output_file=$2

DESTINATION_PATHNAME=/tmp/web
HTML_DESTINATION_PATHNAME="${DESTINATION_PATHNAME}/html"
PANDOC_CONFIG_DESTINATION_PATHNAME="${DESTINATION_PATHNAME}/pandoc-config"

pandoc \
    --css="${HTML_DESTINATION_PATHNAME}/styles.css" \
    --standalone \
    --template="${PANDOC_CONFIG_DESTINATION_PATHNAME}/template.html" \
    -t html \
    "${PANDOC_CONFIG_DESTINATION_PATHNAME}/metadata.yml" \
    $input_file \
    -o $output_file
