#!/bin/bash

input_file=$1
output_file=$2

HTML_DESTINATION_PATHNAME=/tmp/src-html

pandoc \
    --css="${HTML_DESTINATION_PATHNAME}/styles.css" \
    --standalone \
    --template=/tmp/pandoc-config/template.html \
    -t html \
    /tmp/pandoc-config/metadata.yml \
    $input_file \
    -o $output_file
